'use client';

// import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { notFound } from 'next/navigation'
import { Inter } from 'next/font/google'
import './globals.scss'

import { QueryClient, QueryClientProvider } from 'react-query'
import { ReactQueryDevtools } from 'react-query/devtools';
import { ApiProvider } from '@/assets/script/api/context/global'
import { ReactNode } from 'react';
import Navigation from './navigation';

interface LocaleLayoutProps {
  children: ReactNode
  params: { lang: string }
}

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Vupico Next App Exam',
//   description: 'Vupico next app exam, generated by create next app',
// }

// eslint-disable-next-line @next/next/no-async-client-component
export default async function RootLayout({ children, params: { lang } }: LocaleLayoutProps) {
  let messages
  try {
    messages = (await import(`@/locale/${lang}.json`)).default
  } catch (error) {
    // console.error('Failed to load messages:', error);
    notFound()
  }

  // Create a client
  const mainQueryClient = new QueryClient()

  return (
    <html lang={lang}>
      <body className={inter.className}>
        {
          // Provide the client to your App
          <QueryClientProvider client={mainQueryClient}>
            <ApiProvider>
              <NextIntlClientProvider locale={lang} messages={messages} timeZone={'Asia/Singapore'}>
                <main className="main">
                  <Navigation/>
                  {children}
                </main>
              </NextIntlClientProvider>
              <ReactQueryDevtools initialIsOpen={false} />
            </ApiProvider>
          </QueryClientProvider>
        }
      </body>
    </html>
  )
}
