// import styles from './page.module.scss'
import { getTranslations } from 'next-intl/server';
import type { Metadata } from 'next'
import Navigation from './navigation';
import Comments from './comments';

export const metadata: Metadata = {
  title: 'Comments | Vupico Next App Exam',
  description: 'Comments | Vupico next app exam, generated by create next app',
}

export default async function Home() {
  const langTrans = await getTranslations('lang');
  return (
    <main className="main">
      <Navigation/>
      <h1 className="title">{langTrans('comments/title')}</h1>
      <Comments/>
    </main>
  )
}
