import { getTranslations } from 'next-intl/server';
// import type { Metadata } from 'next'
import Domains from './domains';

export const metadata = async () => {
  const langTrans = await getTranslations('lang');
  return {
    title: `${langTrans('domains/title')} | Next Test App`,
    description: `${langTrans('domains/title')} | Next app, generated by create next app`,
  }
}

export default async function Home() {
  const langTrans = await getTranslations('lang');
  return (
    <>
      <h1 className="title">{langTrans('domains/title')}</h1>
      <Domains/>
    </>
  )
}
