import type { Metadata } from 'next'
import Comment from './comment';
import Navigation from '@/app/[lang]/navigation';

export const metadata: Metadata = {
  title: 'Comment | Vupico Next App Exam',
  description: 'Comment | Vupico next app exam, generated by create next app',
}

export default function Home() {
  return (
    <main className="main">
      <Navigation/>
      <Comment/>
    </main>
  )
}
