import { getTranslations } from 'next-intl/server';
// import type { Metadata } from 'next'
import Comment from './comment';

export const metadata = async () => {
  const langTrans = await getTranslations('lang');
  return {
    title: `${langTrans('comment/title')} | Vupico Next App Exam`,
    description: `${langTrans('comment/title')} | Vupico next app exam, generated by create next app`,
  }
}

export default function Home() {
  return (
    <Comment/>
  )
}
