import { getTranslations } from 'next-intl/server';
import type { Metadata } from 'next'
import Domains from './domains';
import Navigation from '@/app/[lang]/navigation';

export const metadata: Metadata = {
  title: 'Domains | Vupico Next App Exam',
  description: 'Domains | Vupico next app exam, generated by create next app',
}

export default async function Home() {
  const langTrans = await getTranslations('lang');
  return (
    <main className="main">
      <Navigation/>
      <h1 className="title">{langTrans('domains/title')}</h1>
      <Domains/>
    </main>
  )
}
