import { getTranslations } from 'next-intl/server';
import type { Metadata } from 'next'
import Posted from './posted';
import Navigation from '@/app/[lang]/navigation';

export const metadata: Metadata = {
  title: 'Posted | Vupico Next App Exam',
  description: 'Posted | Vupico next app exam, generated by create next app',
}

export default async function Home() {
  const langTrans = await getTranslations('lang');
  return (
    <main className="main">
      <Navigation/>
      <h1 className="title">{langTrans('posted/title')}</h1>
      <Posted/>
    </main>
  )
}
