import { getTranslations } from 'next-intl/server';
// import type { Metadata } from 'next'
import Length from './length';

export const metadata = async () => {
  const langTrans = await getTranslations('lang');
  return {
    title: `${langTrans('length/title')} | Vupico Next App Exam`,
    description: `${langTrans('length/title')} | Vupico next app exam, generated by create next app`,
  }
}

export default async function Home() {
  const langTrans = await getTranslations('lang');
  return (
    <>
      <h1 className="title">{langTrans('length/title')}</h1>
      <Length/>
    </>
  )
}
