import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'

// AG Grid CSS
import 'ag-grid-community/styles/ag-grid.css'; // Core CSS
import 'ag-grid-community/styles/ag-theme-quartz.css'; // Theme

import { ReactNode } from 'react';
import ClientLayout from './client-layout';

interface LocaleLayoutProps {
  children: ReactNode
  params: { locale: string }
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Test App',
  description: 'Next app, generated by create next app',
}

const RootLayout = (props: LocaleLayoutProps) => {
  return (
    <html lang={props.params.locale}>
      <body className={inter.className}>
        <ClientLayout { ...props }>{props.children}</ClientLayout>
      </body>
    </html>
  )
}

export default RootLayout