// import styles from './page.module.scss'
import { getTranslations } from 'next-intl/server';
// import type { Metadata } from 'next'
import Comments from './comments';

export const metadata = async () => {
  const langTrans = await getTranslations('lang');
  return {
    title: `${langTrans('comments/title')} | Next Test App`,
    description: `${langTrans('comments/title')} | Next app, generated by create next app`,
  }
}

export default async function Home() {
  const langTrans = await getTranslations('lang');
  return (
    <>
      <h1 className="title">{langTrans('comments/title')}</h1>
      <Comments/>
    </>
  )
}
